// config.js
import cfg from "./config_env_file.js" // this is autogenerated file, see shell_scripts/ in the top directory

export default {
    backendUrl: () => {
        return cfg.FRONTEND_BACKEND_PROTOCOL+ "://" + cfg.FRONTEND_BACKEND_HOSTANDPORT+ "/v1"
    }
}