version: "3.0"
services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: "dbpass"
      MARIADB_DATABASE: "labonedb"
      MARIADB_USER: "dbuser"
      MARIADB_PASSWORD: "dbpass"
    volumes:
      - "./labonedb/config:/etc/mysql/conf.d"
      - "./labonedb/data:/var/lib/mysql"
    ports:
      - "3306:3306"

  lab_one_backend:
    build: ./backend
    ports:
      - "8091:8091"
  
  web:
    image: nginx:latest
    volumes:
      - "./nginx_conf.d:/etc/nginx/conf.d"
      - "./frontend:/usr/share/nginx/html"
    ports:
      - "8080:80"

