version: "3.0"
services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: "dbpass"
      MARIADB_DATABASE: "labonedb"
      MARIADB_USER: "dbuser"
      MARIADB_PASSWORD: "dbpass"
    volumes:
      - "./labonedb/config:/etc/mysql/conf.d"
      - "./labonedb/data:/var/lib/mysql"
    ports:
      - "3306:3306"

  lab_one_backend:
    image: lab_one_backend
    ports:
      - "8091:8091"

  goose:
    image: artsafin/goose-migrations:latest
    volumes:
      - "./labonedb/migrations:/usr/share/migrations"
    working_dir: "/usr/share/migrations"

  web:
    image: nginx:latest
    volumes:
      - "./ssl_box:/ssl_box" # with certificates inside
      - "./nginx_conf.d:/etc/nginx/conf.d"
      - "./frontend:/usr/share/nginx/html"
    ports:
      - "80:80"
      - "443:443"

